import fs from 'node:fs/promises';
import path from 'node:path';
import { buildApprovedAssets } from './assets.js';
import { analyzeSource } from './extractor.js';
import { findJsxFiles } from './scanner.js';

const SIMILARITY_THRESHOLD = 0.6;

export async function runDesignSystemCheck(options) {
  const repoDir = path.resolve(options.repoPath);
  const artifactsDir = path.resolve(options.designSystem);
  const approvedAssets = await loadApprovedAssets(artifactsDir);
  const usages = await scanUsages(repoDir, options.files);
  const violations = findViolations(usages, approvedAssets);
  const text = formatTextReport(violations);

  if (options.report) {
    const reportPath = path.resolve(options.report);
    await fs.mkdir(path.dirname(reportPath), { recursive: true });
    await fs.writeFile(reportPath, formatMarkdownReport(violations), 'utf8');
  }

  return {
    violations,
    text,
    exitCode: violations.length > 0 && options.strict ? 1 : 0,
  };
}

export function findViolations(usages, assets) {
  const approved = assets
    .map((asset) => ({
      asset,
      signature: normalizedClassSet(asset.commonClasses),
      deprecatedSignatures: deprecatedClassSets(asset.deprecatedClasses),
    }))
    .filter((entry) => entry.signature.size > 0 || entry.deprecatedSignatures.length > 0);
  const violations = [];

  for (const usage of usages) {
    const usageSet = normalizedClassSet(usage.classes);

    for (const entry of approved) {
      for (const deprecatedSignature of entry.deprecatedSignatures) {
        const similarity = jaccard(usageSet, deprecatedSignature);
        if (similarity >= SIMILARITY_THRESHOLD) {
          violations.push(buildViolation('deprecated', usage, entry.asset, deprecatedSignature, similarity));
        }
      }

      if (entry.signature.size === 0) {
        continue;
      }

      const similarity = jaccard(usageSet, entry.signature);
      if (similarity >= SIMILARITY_THRESHOLD && similarity < 1) {
        violations.push(buildViolation('near-miss', usage, entry.asset, entry.signature, similarity));
      }
    }
  }

  return violations;
}

export function formatTextReport(violations) {
  if (violations.length === 0) {
    return 'dsg check: no design-system drift found.\n';
  }

  const lines = [
    `dsg check: found ${violations.length} design-system drift warning${violations.length === 1 ? '' : 's'}.`,
    '',
  ];

  for (const violation of violations) {
    lines.push(`${violation.file}:${violation.line}:${violation.column} ${violation.type} ${violation.assetName}`);
    lines.push(`  ${messageFor(violation)}`);
    lines.push(`  similarity: ${violation.similarity.toFixed(2)}`);
    lines.push(`  missing: ${formatClasses(violation.missingClasses)}`);
    lines.push(`  extra: ${formatClasses(violation.extraClasses)}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function formatMarkdownReport(violations) {
  const lines = ['## dsg check', ''];

  if (violations.length === 0) {
    lines.push('No design-system drift found.', '');
    return lines.join('\n');
  }

  lines.push(`Found ${violations.length} design-system drift warning${violations.length === 1 ? '' : 's'}.`, '');
  lines.push('| Location | Type | Asset | Diff |');
  lines.push('| --- | --- | --- | --- |');

  for (const violation of violations) {
    const diff = [
      `missing: ${inlineClasses(violation.missingClasses)}`,
      `extra: ${inlineClasses(violation.extraClasses)}`,
    ].join('<br>');
    lines.push(`| ${escapeMarkdown(`${violation.file}:${violation.line}`)} | ${escapeMarkdown(violation.type)} | ${escapeMarkdown(violation.assetName)} | ${diff} |`);
  }

  lines.push('', '<!-- Generated by dsg check. -->', '');
  return lines.join('\n');
}

async function loadApprovedAssets(artifactsDir) {
  const assets = await readJson(path.join(artifactsDir, 'assets.json'), []);
  if (Array.isArray(assets) && assets.length > 0) {
    return assets;
  }

  const catalog = await readJson(path.join(artifactsDir, 'catalog.json'), null);
  const decisions = await readJson(path.join(artifactsDir, 'decisions.json'), []);
  if (catalog && Array.isArray(decisions)) {
    return buildApprovedAssets(catalog, decisions);
  }

  return Array.isArray(assets) ? assets : [];
}

async function scanUsages(repoDir, filesOption) {
  const relativeFiles = filesOption
    ? await resolveRequestedFiles(repoDir, filesOption)
    : await findJsxFiles(repoDir);
  const usages = [];

  for (const relativeFile of relativeFiles) {
    const absoluteFile = path.join(repoDir, relativeFile);
    const source = await fs.readFile(absoluteFile, 'utf8');
    const analysis = analyzeSource(source, relativeFile);
    usages.push(
      ...analysis.classNameMatches.map((match) => ({ ...match, sourceType: 'className' })),
      ...analysis.cnCalls.map((call) => ({
        file: call.file,
        line: call.line,
        column: call.column,
        element: call.element === 'unknown' ? 'cn()' : call.element,
        classes: call.classes,
        signature: call.signature,
        sourceType: 'cn',
      })),
    );
  }

  return usages;
}

async function resolveRequestedFiles(repoDir, filesOption) {
  const patterns = filesOption
    .split(',')
    .map((pattern) => pattern.trim())
    .filter(Boolean);
  const allFiles = await findJsxFiles(repoDir);
  const selected = new Set();

  for (const pattern of patterns) {
    const normalized = normalizePath(pattern);
    if (hasGlobSyntax(normalized)) {
      const regex = globToRegExp(normalized);
      for (const file of allFiles) {
        if (regex.test(file)) {
          selected.add(file);
        }
      }
      continue;
    }

    selected.add(normalized);
  }

  return [...selected].sort();
}

function buildViolation(type, usage, asset, referenceSet, similarity) {
  const usageSet = normalizedClassSet(usage.classes);
  return {
    type,
    file: usage.file,
    line: usage.line,
    column: usage.column,
    element: usage.element,
    assetName: asset.name || asset.id || 'approved asset',
    assetId: asset.id,
    similarity,
    missingClasses: difference(referenceSet, usageSet),
    extraClasses: difference(usageSet, referenceSet),
  };
}

function deprecatedClassSets(value) {
  if (!value) {
    return [];
  }

  if (typeof value === 'string') {
    return [normalizedClassSet(value.split(/\s+/))].filter((set) => set.size > 0);
  }

  if (Array.isArray(value)) {
    if (value.every((item) => typeof item === 'string')) {
      return [normalizedClassSet(value)].filter((set) => set.size > 0);
    }
    return value.flatMap((item) => deprecatedClassSets(item));
  }

  if (typeof value === 'object') {
    return Object.values(value).flatMap((item) => deprecatedClassSets(item));
  }

  return [];
}

function normalizedClassSet(classes) {
  return new Set((classes ?? []).map((className) => String(className).trim()).filter(Boolean));
}

function jaccard(left, right) {
  if (left.size === 0 && right.size === 0) {
    return 1;
  }

  const intersectionSize = [...left].filter((className) => right.has(className)).length;
  const unionSize = new Set([...left, ...right]).size;
  return unionSize === 0 ? 0 : intersectionSize / unionSize;
}

function difference(left, right) {
  return [...left].filter((className) => !right.has(className)).sort();
}

async function readJson(filePath, fallback) {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') {
      return fallback;
    }
    throw error;
  }
}

function formatClasses(classes) {
  return classes.length > 0 ? classes.join(' ') : '(none)';
}

function inlineClasses(classes) {
  return classes.length > 0 ? classes.map((className) => `<code>${escapeHtml(className)}</code>`).join(' ') : 'none';
}

function messageFor(violation) {
  if (violation.type === 'deprecated') {
    return `${violation.assetName} の deprecated class に近い使用です。承認済み asset に合わせてください。`;
  }

  return `${violation.assetName} にほぼ一致。合わせるか、意図的な差分なら decisions に記録せよ。`;
}

function hasGlobSyntax(value) {
  return /[*?[\]]/.test(value);
}

function globToRegExp(pattern) {
  let source = '^';

  for (let index = 0; index < pattern.length; index += 1) {
    const char = pattern[index];
    const next = pattern[index + 1];
    const afterNext = pattern[index + 2];

    if (char === '*' && next === '*') {
      if (afterNext === '/') {
        source += '(?:.*/)?';
        index += 2;
        continue;
      }
      source += '.*';
      index += 1;
      continue;
    }

    if (char === '*') {
      source += '[^/]*';
      continue;
    }

    if (char === '?') {
      source += '[^/]';
      continue;
    }

    source += escapeRegExp(char);
  }

  source += '$';
  return new RegExp(source);
}

function normalizePath(filePath) {
  return filePath.split(path.sep).join('/');
}

function escapeRegExp(value) {
  return value.replace(/[|\\{}()[\]^$+*?.]/g, '\\$&');
}

function escapeMarkdown(value) {
  return value.replace(/\|/g, '\\|');
}

function escapeHtml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
