import fs from 'node:fs/promises';
import path from 'node:path';

const DEFAULT_REPO_URL = 'https://github.com/mameshivaa/design-system-grower';

// Catch-all roles would dominate the headline and the grade without saying
// anything actionable, so the diagnosis ignores them entirely.
const DIAGNOSIS_SKIPPED_ROLES = new Set(['Other', 'Layout']);

export function buildDiagnosis(catalog = {}, options = {}) {
  const roles = Object.fromEntries(
    Object.entries(catalog.summary?.roles ?? {}).filter(([role]) => !DIAGNOSIS_SKIPPED_ROLES.has(role)),
  );
  const filesScanned = Math.max(1, Number(catalog.summary?.filesScanned ?? 0) || 1);
  const driftCandidates = Number(options.driftCandidates ?? countDriftCandidates(catalog)) || 0;
  const competingFamilies = Number(catalog.summary?.competingFamilies ?? catalog.competingFamilies?.length ?? 0) || 0;
  const roleEntries = sortedRoleEntries(roles);
  const repoName = options.repoName ?? repoNameFor(catalog.target);
  const repoUrl = options.repoUrl ?? DEFAULT_REPO_URL;
  const generatedAt = options.generatedAt ?? catalog.generatedAt ?? new Date().toISOString();
  const date = generatedAt.slice(0, 10);

  // Grade formula:
  // raw = max(0, roleVariants - roleCount) * 1.2
  //     + roleCompetingFamilies * 5
  //     + driftCandidates * 2
  // normalized = raw / sqrt(filesScanned)
  // A <= 1, B <= 2, C <= 4, D <= 7, E <= 11, otherwise F.
  const variantCount = roleEntries.reduce((sum, [, summary]) => sum + Number(summary.variants ?? 0), 0);
  const roleCompetingFamilies = roleEntries.reduce((sum, [, summary]) => (
    sum + Number(summary.competingFamilies ?? 0)
  ), 0);
  const rawScore = Math.max(0, variantCount - roleEntries.length) * 1.2
    + roleCompetingFamilies * 5
    + driftCandidates * 2;
  const normalizedScore = rawScore / Math.sqrt(filesScanned);
  const grade = gradeFor(normalizedScore);
  const worstConflict = worstConflictFor(catalog);

  const lines = [
    'Design System Diagnosis',
    `Repo: ${repoName}`,
    `Date: ${date}`,
    '',
    `UI Chaos Grade: ${grade}`,
    `Basis: ${variantCount} role variants, ${competingFamilies} competing families, ${driftCandidates} drift candidates, ${filesScanned} files scanned.`,
    '',
    'Role summary:',
  ];

  if (roleEntries.length === 0) {
    lines.push('- No repeated UI roles detected.');
  } else {
    for (const [role, summary] of roleEntries) {
      const variants = Number(summary.variants ?? 0);
      const familyCount = Number(summary.competingFamilies ?? 0);
      const example = summary.topExample ? `; example: ${summary.topExample}` : '';
      lines.push(`- ${role}: ${variants} variant${variants === 1 ? '' : 's'}, ${familyCount} competing ${familyCount === 1 ? 'family' : 'families'}${example}`);
    }
  }

  lines.push('', 'Worst competing family:');
  if (!worstConflict) {
    lines.push('- None detected.');
  } else {
    lines.push(`- ${worstConflict.label}`);
    for (const side of worstConflict.sides) {
      lines.push(`  - side ${side.side}: ${side.occurrences} use${side.occurrences === 1 ? '' : 's'}; ${side.className}`);
    }
  }

  lines.push('', `Generated by design-system-grower - ${repoUrl}`, '');

  const text = `${lines.join('\n')}\n`;
  return {
    grade,
    score: Number(normalizedScore.toFixed(2)),
    text,
    markdown: buildDiagnosisMarkdown(text, { grade, score: normalizedScore, repoName, date, repoUrl }),
  };
}

export async function writeDiagnosis(catalog, outputDir, options = {}) {
  const diagnosis = buildDiagnosis(catalog, options);
  const outputPath = path.join(path.resolve(outputDir), 'diagnosis.md');
  await fs.writeFile(outputPath, diagnosis.markdown, 'utf8');
  return {
    ...diagnosis,
    outputPath,
  };
}

export async function regenerateDiagnosis(artifactsDir, options = {}) {
  const resolvedArtifactsDir = path.resolve(artifactsDir);
  const catalog = JSON.parse(await fs.readFile(path.join(resolvedArtifactsDir, 'catalog.json'), 'utf8'));
  return writeDiagnosis(catalog, resolvedArtifactsDir, options);
}

function buildDiagnosisMarkdown(text, metadata) {
  return [
    '# Design System Diagnosis',
    '',
    `- Repo: ${metadata.repoName}`,
    `- Date: ${metadata.date}`,
    `- UI Chaos Grade: ${metadata.grade}`,
    `- Score: ${metadata.score.toFixed(2)}`,
    `- Repo URL: ${metadata.repoUrl}`,
    '',
    '## Copy Block',
    '',
    '```text',
    text.trimEnd(),
    '```',
    '',
  ].join('\n');
}

function sortedRoleEntries(roles) {
  return Object.entries(roles)
    .sort((a, b) => (
      Number(b[1].variants ?? 0) - Number(a[1].variants ?? 0)
      || Number(b[1].competingFamilies ?? 0) - Number(a[1].competingFamilies ?? 0)
      || a[0].localeCompare(b[0])
    ));
}

function countDriftCandidates(catalog) {
  return (catalog.candidates ?? []).filter((candidate) => (
    candidate.actionType === 'canonicalize' || candidate.driftId
  )).length;
}

function gradeFor(score) {
  if (score <= 1) return 'A';
  if (score <= 2) return 'B';
  if (score <= 4) return 'C';
  if (score <= 7) return 'D';
  if (score <= 11) return 'E';
  return 'F';
}

function worstConflictFor(catalog) {
  const family = [...(catalog.competingFamilies ?? [])]
    .sort((a, b) => (
      Number(b.score ?? 0) - Number(a.score ?? 0)
      || Number(b.occurrences ?? 0) - Number(a.occurrences ?? 0)
      || String(a.id ?? '').localeCompare(String(b.id ?? ''))
    ))[0];
  if (family) {
    return conflictFromFamily(family);
  }

  const candidate = [...(catalog.candidates ?? [])]
    .filter((item) => item.actionType === 'canonicalize' || item.driftId)
    .sort((a, b) => Number(b.score ?? 0) - Number(a.score ?? 0))[0];
  return candidate ? conflictFromFamily(candidate) : null;
}

function conflictFromFamily(family) {
  const sides = (family.sides ?? [])
    .slice(0, 2)
    .map((side) => ({
      side: side.side,
      occurrences: Number(side.occurrences ?? 0),
      className: side.className ?? (side.classes ?? []).join(' '),
    }));
  if (sides.length === 0) {
    return null;
  }

  const label = family.id
    ? `${family.id} across ${Number(family.occurrences ?? 0)} total uses`
    : `${Number(family.occurrences ?? 0)} total uses`;
  return { label, sides };
}

function repoNameFor(target) {
  if (!target) {
    return 'unknown';
  }
  return path.basename(path.resolve(target));
}
